//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngryMouse.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double CursorGrowthRate {
            get {
                return ((double)(this["CursorGrowthRate"]));
            }
            set {
                this["CursorGrowthRate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MaxCursorSize {
            get {
                return ((int)(this["MaxCursorSize"]));
            }
            set {
                this["MaxCursorSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int CursorAnimationLength {
            get {
                return ((int)(this["CursorAnimationLength"]));
            }
            set {
                this["CursorAnimationLength"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int CursorVisibleDuration {
            get {
                return ((int)(this["CursorVisibleDuration"]));
            }
            set {
                this["CursorVisibleDuration"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShakeActivationEnabled {
            get {
                return ((bool)(this["ShakeActivationEnabled"]));
            }
            set {
                this["ShakeActivationEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HotkeyActivationEnabled {
            get {
                return ((bool)(this["HotkeyActivationEnabled"]));
            }
            set {
                this["HotkeyActivationEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hold")]
        public string HotkeyActivationMode {
            get {
                return ((string)(this["HotkeyActivationMode"]));
            }
            set {
                this["HotkeyActivationMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public string HotkeyModifiers {
            get {
                return ((string)(this["HotkeyModifiers"]));
            }
            set {
                this["HotkeyModifiers"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string HotkeyKey {
            get {
                return ((string)(this["HotkeyKey"]));
            }
            set {
                this["HotkeyKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideBuiltInCursor {
            get {
                return ((bool)(this["HideBuiltInCursor"]));
            }
            set {
                this["HideBuiltInCursor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System")]
        public string CursorSourceMode {
            get {
                return ((string)(this["CursorSourceMode"]));
            }
            set {
                this["CursorSourceMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Adwaita")]
        public string CursorCollectionName {
            get {
                return ((string)(this["CursorCollectionName"]));
            }
            set {
                this["CursorCollectionName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public string ThemeMode {
            get {
                return ((string)(this["ThemeMode"]));
            }
            set {
                this["ThemeMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartMinimizedToTray {
            get {
                return ((bool)(this["StartMinimizedToTray"]));
            }
            set {
                this["StartMinimizedToTray"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugEnabled {
            get {
                return ((bool)(this["DebugEnabled"]));
            }
            set {
                this["DebugEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastImportCollectionFolder {
            get {
                return ((string)(this["LastImportCollectionFolder"]));
            }
            set {
                this["LastImportCollectionFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastImportSettingsFolder {
            get {
                return ((string)(this["LastImportSettingsFolder"]));
            }
            set {
                this["LastImportSettingsFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastExportSettingsFolder {
            get {
                return ((string)(this["LastExportSettingsFolder"]));
            }
            set {
                this["LastExportSettingsFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomCursorPath {
            get {
                return ((string)(this["CustomCursorPath"]));
            }
            set {
                this["CustomCursorPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CustomCursorHotspotX {
            get {
                return ((int)(this["CustomCursorHotspotX"]));
            }
            set {
                this["CustomCursorHotspotX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CustomCursorHotspotY {
            get {
                return ((int)(this["CustomCursorHotspotY"]));
            }
            set {
                this["CustomCursorHotspotY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ShakeTrackingInterval {
            get {
                return ((int)(this["ShakeTrackingInterval"]));
            }
            set {
                this["ShakeTrackingInterval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ShakeMinimumSpeed {
            get {
                return ((double)(this["ShakeMinimumSpeed"]));
            }
            set {
                this["ShakeMinimumSpeed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ShakeMinimumTurns {
            get {
                return ((int)(this["ShakeMinimumTurns"]));
            }
            set {
                this["ShakeMinimumTurns"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EmergencyExitEnabled {
            get {
                return ((bool)(this["EmergencyExitEnabled"]));
            }
            set {
                this["EmergencyExitEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F12")]
        public string EmergencyExitKey {
            get {
                return ((string)(this["EmergencyExitKey"]));
            }
            set {
                this["EmergencyExitKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOverrideSystemCursor {
            get {
                return ((bool)(this["AlwaysOverrideSystemCursor"]));
            }
            set {
                this["AlwaysOverrideSystemCursor"] = value;
            }
        }
    }
}
